---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-poller-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: unifi-poller-secret
    creationPolicy: Owner
  data:
    - secretKey: USERNAME
      remoteRef:
        key: /unifi-poller/USERNAME
    - secretKey: PASSWORD
      remoteRef:
        key: /unifi-poller/PASSWORD
