# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-poller-secret
stringData:
  username: ENC[AES256_GCM,data:Fxq1LX5dfzGLxE4=,iv:8appdQ/JraDA1uvEzHgH50H6WyCEe/e5lEBppGhrrKc=,tag:PBjxsIzC2olUxCI0//A3Dg==,type:str]
  password: ENC[AES256_GCM,data:mXq5CW28CpweVls9q1ZMKg==,iv:cP49DxYmqvUnt73IgCag4254pa4tcWPzGnMwHfEKIqQ=,tag:AN869p5G0EuzbgZDQ6Y8ZQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodnYraTVycTlHM1lTTGF0
        YnNYcDlGM3pYTkdEbEhLMVVLS0Nsa3NNSFFnCmhqbGg0bStjMkpXZDMwOWhMQXhP
        dVVRRzFwRDdOaTd1cEw2R3cya0dJZGcKLS0tIFpNUFpKeE1RUmEyOExMbFBNa2Mw
        SEN6eXU1MlVvNmQrcm9BcjllRlF1M2MKeBmeJecSXejzakBmJEawmNjM3z0ipNIP
        AN7PqMYvD9WKO3YidXe7xbphmT2iC8m0V3ntfbfnxnh4P2iWS69Qyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T21:29:56Z"
  mac: ENC[AES256_GCM,data:+oKrhfv6GcOVttNqtRA3q0/Gcn3MZyTQ+8u9sZ0Xl81Td0eH5pxOcVAk0HPvqk/cz0f8Ol0EAjppRiSZbEOfqLTKDDSt7cgkbkmlpN/PqxO9JhqgOZrekJivFZ564fmzuseCjMnZRQ7IGC+DHX13dFyhJRvFJFhl/d3jTn+Zx8g=,iv:pZTL/rGjMXM3d9W3VaSfO/Tj4hkD7nZFHaPDZA8Z7AQ=,tag:QMfmxf16KExWG4IScjk3qg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
