---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-internal-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: security-authentik@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: traefik
    gethomepage.dev/name: Traefik Internal
    gethomepage.dev/group: Network
spec:
  ingressClassName: internal
  rules:
    - host: &host "traefik-internal.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-internal
                port:
                  number: 8080
