# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: infisical-auth
    namespace: kube-system
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:fir99jf5LzpAvQOCdF49HEzJ+oCAboDlmvyufJ7fa6EpWLhB,iv:8py6uACOE+XbFzpOyvIed8jzEZ3+L/G1UchYsGbRfzs=,tag:2I/xr+bG0xzgowTG+1RazA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:wcrHy5qbA8ApXg0NeCN62AM9vgFak8WcWqvLkoXrzYJLgCrpCgXAkOleB7H5iADnnIQOrTpD7YtuTiRjtP+yYg==,iv:02AoGFo5IOBbMqjADmVl6RULxWRXLsbtV47s7mp930E=,tag:fDpe7UBb7T56DeP49tzjFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbksxU242Y3poeWFvc3Vt
            WUMyN0srYVZWUFM3MDRnaG8zS1BXcHdOVW1zCndqbHdWSS9Nd1A3emZLU2JSSDd5
            VytvSTVUbUROM3lyMVhzMGVqaWRGNTQKLS0tIGxJYVZCZmh0MTBsWDczVVFuOGpw
            ZW5VU0xsaTU4bk0zWkllWUNlelNKVkUKZXQUDi0sF6EaGtSGpXRIGjAyPPhIvOQI
            bzM015DE0WLoGGcu9/L8umueF6f5/a4/PMwxF2oP98vCb9H+3bkRrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:20:17Z"
    mac: ENC[AES256_GCM,data:UgCLSyqCnllob8Wux/9Du+EWD/aIgSXeRYFi1ElCWKdu4ALLchNFQ3wtCQGbr67h2iRPEQF4retY0luUNxH4p+gOEdrwHmB8XS0ExWs+CF2KrPpbYG1XYW9CuRu/HTMFNULP+l5LQWsm2fm/dIIzX4L4WhTA7VyQbsF+9zpHvmM=,iv:UCS1V3U/ry2wRsKuIPSnnjevXfHz2FEG4p5VpHrKcVs=,tag:hjGiHo1DXi2PbS3U8ddvrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
