---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            namespace: kube-system
            key: CLIENT_ID
          clientSecret:
            name: infisical-auth
            namespace: kube-system
            key: CLIENT_SECRET
      secretsScope:
        projectSlug: talos-homelab-cluster
        environmentSlug: prod
