---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: QBT_USERNAME
      remoteRef:
        key: /qbittorrent/QBT_USERNAME
    - secretKey: QBT_PASSWORD
      remoteRef:
        key: /qbittorrent/QBT_PASSWORD
