# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: booklore-secret
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:99kENa6qXQ7S180VkvmivQ==,iv:C7ZcHtC1uY/k2FN43hNS26g+BiK/DQyA6CZGkXl/UlI=,tag:GVddTSikNmuh2eQYWVLPoQ==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:yK3oSBiE6r8AIZAJc4Pfgw==,iv:UDhXc7i3SlopYM5Qn1BY246KPo0c2GrCzSUGB3QX2+M=,tag:Ts3Gt7TcDbwftJiq9p8Z6Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNHJTM0k3NEkwTWNpNUNs
        VFZsRVJ0MnExb3Era0NtVUdUSjZwdHNISFRzCjdCYjJhdG9BMnRlU3YwbXBWQ0VY
        ZjQzNHlFaXlCcDNBVlMrV0xDYnlKb3MKLS0tIDRGODZrOWRuekRpbWk5dm5HUXBO
        RkJKS3FzTkdvNy84dS9ZMUpWZ1BhVEkKsLSFetlPFI6KWMlk4mp8x3alrl9QbS/s
        CEr4QXK2b1NwgSOlgOndtlnISkjdP85cSYkXHBxK3fPxVFBE+7Nj/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T21:28:05Z"
  mac: ENC[AES256_GCM,data:r/EH0NHu4W63h6Ftb+ENXbkUgdrhFqQOC3+uOQPq4zYuutfvOO66w2mzVpd/SrntmpGFq34tND1OhwRRYjYMCdxoTEO3H+RFRkMbqZhrJ2RgzEAbtqzSkNqQelOvZWtHZVuIhsk5gQuGJyVbSC9P3JwafMcTB1WH1S18F1IYsFg=,iv:oB2Can9u32DLNfZEAeho7q6C/cEeF6E5cGI6gLMp6FQ=,tag:sxBcueNphlvde93XYoXpIQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
