# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: booklore-secret
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:99kENa6qXQ7S180VkvmivQ==,iv:C7ZcHtC1uY/k2FN43hNS26g+BiK/DQyA6CZGkXl/UlI=,tag:GVddTSikNmuh2eQYWVLPoQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:yK3oSBiE6r8AIZAJc4Pfgw==,iv:UDhXc7i3SlopYM5Qn1BY246KPo0c2GrCzSUGB3QX2+M=,tag:Ts3Gt7TcDbwftJiq9p8Z6Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oxpQx/PnwZnMZrmOz154XwYhFU7mb2Gu2u7CQlAjYZSVZ7k5QxO4ePlR6JgvGKhta3LbtcJUwiiz,iv:7CZkvzBiS6HN3Td/Xm9w05N1IHW0ZMQSz4HlxkGEvfM=,tag:gvj7hlvoRAvLcU1eJ8ZEtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNHJTM0k3NEkwTWNpNUNs
            VFZsRVJ0MnExb3Era0NtVUdUSjZwdHNISFRzCjdCYjJhdG9BMnRlU3YwbXBWQ0VY
            ZjQzNHlFaXlCcDNBVlMrV0xDYnlKb3MKLS0tIDRGODZrOWRuekRpbWk5dm5HUXBO
            RkJKS3FzTkdvNy84dS9ZMUpWZ1BhVEkKsLSFetlPFI6KWMlk4mp8x3alrl9QbS/s
            CEr4QXK2b1NwgSOlgOndtlnISkjdP85cSYkXHBxK3fPxVFBE+7Nj/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T21:42:16Z"
    mac: ENC[AES256_GCM,data:sdMPk1pWdpqD0D/bo5l++aGE8uFVD1UELYBo6Wt6a4voY6gz3EMQYCAMKBhirLPRrplozabxAbzboL36siNzHmeCoa7sg0iRYI4KdFy/Szz3sO+1nevM7hT06NG/eddQ6ZhztWp2RnaCJ1tMqLPvTU7l1c5DdfQW2qpFXDi8Uno=,iv:aJjCiVUOWlDSbDLC0mACtK2sZF3IG/i687/OHQ/e0uE=,tag:i/V7oKYzf2iAA4DQ2EUQtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
