# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: booklore-secret
    namespace: media
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:99kENa6qXQ7S180VkvmivQ==,iv:C7ZcHtC1uY/k2FN43hNS26g+BiK/DQyA6CZGkXl/UlI=,tag:GVddTSikNmuh2eQYWVLPoQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:yK3oSBiE6r8AIZAJc4Pfgw==,iv:UDhXc7i3SlopYM5Qn1BY246KPo0c2GrCzSUGB3QX2+M=,tag:Ts3Gt7TcDbwftJiq9p8Z6Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JQrDAhhQRNlFithmut34Kxu233U04DItJgWwxxLF1cG5pQHhCiw=,iv:rizrPwmpgR4GehoAsSLjWb/hM5HxBGUEhUQhxKWf7LQ=,tag:wCOQSvkEJiDDxeyOub1DLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNHJTM0k3NEkwTWNpNUNs
            VFZsRVJ0MnExb3Era0NtVUdUSjZwdHNISFRzCjdCYjJhdG9BMnRlU3YwbXBWQ0VY
            ZjQzNHlFaXlCcDNBVlMrV0xDYnlKb3MKLS0tIDRGODZrOWRuekRpbWk5dm5HUXBO
            RkJKS3FzTkdvNy84dS9ZMUpWZ1BhVEkKsLSFetlPFI6KWMlk4mp8x3alrl9QbS/s
            CEr4QXK2b1NwgSOlgOndtlnISkjdP85cSYkXHBxK3fPxVFBE+7Nj/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T22:47:14Z"
    mac: ENC[AES256_GCM,data:v5qldHPs75RNFKS8izyuQ5V2sMEoh4RkrJJgsXhPkUU+iSYUTMTynAG5vi/ElPoxHEDDClXWKGPyEKQlUHXlO/iOy47JK6Yf5OqyjsSE169Ocn4VtgxKYKQVAMVn4Oi31WvabAJZXF+LCLY4+NbLk8Jjaked+85MSnJSfsgiXvI=,iv:3RYTcJg/1relNyvS2PSRmlOLMDk9hGrM26GZQi0Kfy0=,tag:9S8jxzWmAdv1TM+oOyqzGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
