# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D3xZf0r5Ybf7,iv:HD0titSqxlje4gdN+eR683QTfCFxuE/UODLNPTrGr5A=,tag:vhzK6S2qMI3/41eq7DaI4Q==,type:str]
    SECRET_NFS_DOMAIN: ENC[AES256_GCM,data:1srSIYm5Nc0NoK+gEw==,iv:Eaw0HQU/xfmRqU2Pfff34Hn3uitbe/N+hmEQCLaHogU=,tag:sjsMkjKLIbEbbvyQtPbntg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:l8T4DlczwTes5J1MHaBGpFkCAdf9+g==,iv:AURvADK52DWbpIVZuV1LBMG2aJauYwKjXuZuGXPR9p8=,tag:OJkZpZfKDZH/MyKCduEGVQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0VY7wx1nvsabqsexmI5COHVM9yoZ+jNduYCOMPxWBiVDzBGE,iv:j5rcET6iC14E63Js++OWF2p3rmQVPf4FySg5PvZpRb0=,tag:eGiEfjX5HZSkPIxr/YjA0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN1VmMHdqcTFkUS9wM1hn
            emNodldlbGFwVmJUellSd0VrWER5YkpQREM0CnJNcXVXU2pmNjM1RGovTG5xdFJX
            ZVc5QkdhMEJ1TUJyYXpjNmRycFVrWXcKLS0tIGxJZ2JxNnJkNmQ1eHdOVjRzTjdj
            akxzY0RrYWpGVU5aSVhXUFQ1b3JJTDAKy5yrbB/IOdNmrrJldm9K+UGHmkm3ecXZ
            INInHx8vD8i8qAyEdBpw5O4P0yVn9tV+zdotNH2QNC8JL2FgBsCdWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T18:08:59Z"
    mac: ENC[AES256_GCM,data:xjNM4zH1Wb25XsCXAAwFM6k8kXEnxr2ygIGATPU3f7E1DQVvzmuyO/TTOYQFQYA4GcC9uJ2u/WFiQaLGuxZOxyyaVvBkRB97Xq6dkmls0kYEhurBNcJvFas7nBXMD/EHVo+yWy4wyllfdcRWC+epFFsm0xfWbbJVnm/YVt+Y39U=,iv:SUSx5BsYSKE7Reu19a5e2n4Q7/GeKVcBm6bOLnOSh40=,tag:FSYmIL9vi88P+zTw1CW+ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
