---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cluster-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: /cluster-settings/SECRET_DOMAIN
    - secretKey: SECRET_NAS_IP
      remoteRef:
        key: /cluster-settings/SECRET_NAS_IP
    - secretKey: SECRET_ACME_EMAIL
      remoteRef:
        key: /cluster-settings/SECRET_ACME_EMAIL
    - secretKey: SECRET_CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: /cluster-settings/SECRET_CLOUDFLARE_TUNNEL_ID
