# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-secret
stringData:
  api-key: ENC[AES256_GCM,data:uXlt/FoIHEc2X2u6i5EmovcoH/R6HvjA0+wOH6vr3ng=,iv:qR1XzxJJg5/EOEAv6p1I9oC8loj4jZAY8DHpZimNOmA=,tag:l391DLirCfo4LTkwGDpfEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQUNoU0NMdGVlZndMWXFa
        eEwyTVBRc1R1dVNCbmxZNzlrWExHSkd4SzBrCk9FNnhXRHROS2F3WjgyM1Ywd3FY
        WDZpVEpYc20wdTZmYkxheUhSaDgwVmcKLS0tIHhnTFJnNTRkaStSM0VCZW9lK1Vh
        NDBiWFA2OXBHUzFqZ0RyR3NjRGRUWHMK/bok2r8vhHsZa73rzktLooXB9PnrI3Cf
        pQkd6sf2sFSFM3i+JSaVN2sTZPC1+txUhTKUfyia0TvoyNVNGGV/kA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T21:00:55Z"
  mac: ENC[AES256_GCM,data:9DciwEm0lXAja34+0xLBfVWCIgIEWMH1grMlXWFGvMbpMd2LZQ69Vo7x3gcoBwTW0NPetb4d4rQBwsuEeplfGLjLUfdS3Us6YykMIO7wPjjAIfADQq78e57YZoOvoyV3XzG28I1otpW2sY+pcmKmfvwQI3dkZ+VTHL4OpXLWX6k=,iv:Iv0vQ4iVdVeXDq6fQmqy2vuYjUCl6iNlkno1av2Hbio=,tag:aMGv6UUkFO8TBDgW4rMFbg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
