---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: homepage-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_ALLOWED_HOSTS
      remoteRef:
        key: /homepage/HOMEPAGE_ALLOWED_HOSTS
    - secretKey: HOMEPAGE_VAR_ADGUARD_USERNAME
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_ADGUARD_USERNAME
    - secretKey: HOMEPAGE_VAR_ADGUARD_PASSWORD
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_ADGUARD_PASSWORD
    - secretKey: HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID
    - secretKey: HOMEPAGE_VAR_CLOUDFLARED_TUNNELID
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_CLOUDFLARED_TUNNELID
    - secretKey: HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN
    - secretKey: HOMEPAGE_VAR_GRAFANA_HOST
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_GRAFANA_HOST
    - secretKey: HOMEPAGE_VAR_GRAFANA_USERNAME
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_GRAFANA_USERNAME
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_GRAFANA_PASSWORD
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_JELLYFIN_API_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_PROWLARR_API_KEY
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_SABNZBD_API_KEY
    - secretKey: HOMEPAGE_VAR_UNIFI_HOST
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_UNIFI_HOST
    - secretKey: HOMEPAGE_VAR_UNIFI_API_KEY
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_UNIFI_API_KEY
    - secretKey: HOMEPAGE_VAR_SECRET_DOMAIN
      remoteRef:
        key: /homepage/HOMEPAGE_VAR_SECRET_DOMAIN
