# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_ALLOWED_HOSTS: ENC[AES256_GCM,data:ZJ+dRk1oGUw7B3NFRmMEDhkN2fOtP6FHaw==,iv:4c0u8uTBv795BefPlwE5bSNcZbN/SSpDmg1tI+RAZWI=,tag:UbNdGklVbYuRqayOlPQamw==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:piTYnVexruGkUrrh7XzbwRGpsRi55+Zu9o1ZPjtxxFQ=,iv:IiLUm3yWPRTY0/OlWyDGA1ejeDOm813P/4NRa6CFRXQ=,tag:oEfn3AdRjX35k+kK68k4NQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:ABtPBmS8KYKXd3lip01WUFRCBn2xjyL5QQ8OrrwydSqh9pM+,iv:oe/4xkZcEQY5VXbBFfyxK9ZVAer/Vx3qap0eB0/tCdM=,tag:bzNWMsMD3RAuG61wR0J+jg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:g9rYDuUH7x7zPqYByA8sStD3sOTWLF58OG6TEkLrAhP3ObNY++F0Sw==,iv:LGJ4RLOLNP1Eayv9gXtTZ+sXADjcRsRB5qXQNMZec2I=,tag:qDTOkdDnd4fCwf+L8/fvUQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_HOST: ENC[AES256_GCM,data:/7FEW3Wyuan2Ad9WhMpt9tSkudZHwj+wdT5nJ6dmVes0Iw7nlCURMv1sJMQcLQ==,iv:N+v3tB7PfXwja3DaJxgXmkdkiIClo1r3a4D+n+tk1Zs=,tag:0U6vlL2b61tkKXUUtiYhPg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:eHbWAHyyNcc=,iv:5MS9dUecQKfDedCxLyr524aJgLxsq5BTCWcq7WThkz0=,tag:Xxhmly/PvAIBKE8vTKQSJA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:6e0gAzhZWapUJIEPylptEw==,iv:9cGjaSjy67IaocmBt7Kz+ERYn1SS58mXenWQupaR1nk=,tag:ER/uOdl6sXFMwHjjSKPpoA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:Suk1z+LGNQ0GoC1pf9KQ6Jfq396L2L4kP4/xjviQ98c=,iv:zHIFzOvq3Ndy+6H3m5G2aYrUoc1YsQTP9hSwA6u/lJ0=,tag:vPSOtN+ciMAFJggkJ0uCSg==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:h6Zxcv6WQl+lVAWvZbaVZ16Lm/o4QEIRfLbKc6nhHFw=,iv:OHfY1wLcHTFyWiudmc2r9HK247WVj5nyf93cYOX6m7s=,tag:xeP5yLq3p1i2pymXfsJ0ig==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:tuYG1OgQLM8TWdr462TuD2GXF9BEmGSBhpNzYUU6yVU=,iv:vs1aRZMfM+LnFaDxkvmYshBUb5g+gLxjGZyYHkVPruk=,tag:p09PHfWp4MXM3jheaMozRw==,type:str]
    HOMEPAGE_VAR_READARR_API_KEY: ENC[AES256_GCM,data:wHOO0rWFOtQMriMTwS1sIb7YCW+uScN4qADU3n0F7YM=,iv:8eaPC6/LppG0T0GcXl/B3OeM5W1ZbPseJYbtA3SrvyI=,tag:KYtm3B6ATpcRNScZl7biNA==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:5qVkaWXZnKGI6FackLhobbW7p+82LsQxRcYh9PGqNSI=,iv:HBscx8GpkzTp1PdxpZZ+g2oa4LnrTwJhn9q2xiNElbQ=,tag:gFW252+XmW1d6/9a20369Q==,type:str]
    HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:hlnn2roYejBcdN2aaWHm5HrhUig7HKOUeZw+mLMRego=,iv:xi9Wpat/jtSyUJgHwJrqN+loq9IQbUmjut/hspoftr8=,tag:SW+dZeJlCbVKPGVOj+cX5g==,type:str]
    HOMEPAGE_VAR_UNIFI_HOST: ENC[AES256_GCM,data:/CnnlLTFDKxHn1r4oFjKWgbtz1+/pSvbvHOB93dB,iv:M1rBRpu390VWSVmWLOGBf65IlsjH38I0MxaD9TPNt80=,tag:0zowBweguL0jqUfjTBSN1w==,type:str]
    HOMEPAGE_VAR_UNIFI_API_KEY: ENC[AES256_GCM,data:N5HmS2YkNxqT8X4tjMB+I/iOr1SN/2tEFFxi4uKw+34=,iv:AB166iDXf8nd/D16AM+XUvbJWaahd42UhY0Vn7KgYr8=,tag:rFBSGpowkaFj3QP+ILQuAg==,type:str]
    HOMEPAGE_VAR_SECRET_DOMAIN: ENC[AES256_GCM,data:fIITBdlKowCW,iv:U5nmjzrVyIceK7IfqNym+FcPfpuYGrnBM3qp9bZORmQ=,tag:ZKcgsRe0m63bOrmM6s/NDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q4usnvl8t94k908edj27fz9m0k60558fvukfna0su8jya4k0duyqc2vlqk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhblE2bEZobUpnelNxR2xX
            RGpyemJYVnBkbXhEWW9rcGd3Zy9kL0JiVm5vClVDQVJLeXBhZDdQMUZPYjJ2SzRy
            aXFaNVd0a3grMWJRT2FBZlJSU056elkKLS0tIHZQWkprOWdJN2JLbWZqM1ZaTmhv
            Tk52WXJZc25yYUxnSVdSNGhmREU2MFkKjlu7u5j3ycDozLCUeil4ZaCtjxpw9/sk
            XcMr6PE8iZ3itlVY728PvLUf3Trp4sPaedRX8TtBagupV3x2CqAf+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T17:55:39Z"
    mac: ENC[AES256_GCM,data:fJGcTxjdo/YK0SQlaMuqmIlTcnrQjUaE9rJfhfWWgvqbqGFNsqotzHjhBoNBIZvFmGb3sngZQ/lZmk8Hodw5m2EiXbDmDiGiKAYwy+xZ5pDtFZaFa17Cb4gbgODSr8lePmkJaLN0z/cCsItGcMGS6GtCH+TnqqzvATXRWhHH/NQ=,iv:e1iNmcttriQQ7V78OG7qIMRHgHcwoV50rTgLzarue9Q=,tag:LjaGCkTjlT2rGzu5x9d7LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
